[package]
name = "e62rs"
version = "0.7.0"
edition = "2024"
description = "An in-terminal E6 browser."
license-file = "LICENSE"
categories = ["command-line-interface"]
readme = "README.md"
homepage = "https://github.com/TheBearodactyl/e62rs"
repository = "https://github.com/TheBearodactyl/e62rs"
keywords = ["e621", "e926", "tui", "browser"]

[dependencies]
async-trait = "0.1.89"
axum = "0.8.6"
base64 = "0.22.1"
bincode = { version = "2.0.1", features = ["serde"] }
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive", "wrap_help"] }
color-eyre = "0.6.5"
config = "0.15.18"
csv = "1.4.0"
demand = { git = "https://github.com/TheBearodactyl/demand", version = "1.7.2" }
dirs = "6.0.0"
enum-display = "0.2.1"
flate2 = "1.1.5"
futures = "0.3.31"
futures-util = "0.3.31"
hex = "0.4.3"
icy_sixel = "0.1.3"
image = "0.25.8"
indicatif = "0.18.2"
jwalk = "0.8.1"
lazy_static = "1.5.0"
num_cpus = "1.17.0"
open = "5.3.2"
owo-colors = "4.2.3"
rapidfuzz = "0.5.0"
rayon = "1.11.0"
redb = "3.1.0"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["json", "stream"] }
rocket = { version = "0.5.1", features = ["json"] }
schemars = "1.0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
smart-default = "0.7.1"
strip-ansi-escapes = "0.2.1"
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
termcolor = "1.4.1"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
tower-http = { version = "0.6.6", features = ["fs", "cors"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
url = "2.5.7"
urlencoding = "2.1.3"
