post_count = 320
base_url = "https://e621.net"
blacklist = [
    "young",
    "rape",
    "feral",
    "bestiality",
]

[display]
width = 800
height = 600
image_when_info = true
sixel_quality = 100
resize_method = "lanczos3"

[http]
pool_max_idle_per_host = 32
pool_idle_timeout_secs = 90
timeout_secs = 30
connect_timeout_secs = 10
max_connections = 15
http2_prior_knowledge = true
tcp_keepalive = true
tcp_keepalive_secs = 60
user_agent = "e62rs/v0.8.1 (by bearodactyl on e621)"

[cache]
enabled = true
cache_dir = ".cache"
ttl_secs = 3600
tti_secs = 1800
max_size_mb = 500
max_entries = 10000
use_lru_policy = false
enable_stats = true
cleanup_interval_secs = 300
enable_compression = false
compression_level = 6

[cache.posts]
enabled = true
max_posts = 50000000
wal = true
page_size_kb = 4
auto_compact = true
compact_threshold_percent = 25

[performance]
concurrent_downloads = 15
prefetch_enabled = true
prefetch_batch_size = 10
preload_images = true
max_preload_size_mb = 100

[ui]
progress_refresh_rate = 20
detailed_progress = true
auto_clear_progress = true
pagination_size = 20
colored_output = true
sfx = false
progress_format = "MegaBytes"

[search]
min_posts_on_tag = 2
min_posts_on_pool = 2
show_inactive_pools = true
sort_pools_by_post_count = false
sort_tags_by_post_count = true
min_post_score = 0
max_post_score = 9223372036854775807
reverse_tags_order = false
fetch_threads = 8

[login]
login = true
username = ""
api_key = ""

[completion]
tag_similarity_threshold = 0.8
tags = "data/tags.csv"
aliases = "data/tag_aliases.csv"
implications = "data/tag_implications.csv"
pools = "data/pools.csv"

[autoupdate]
tags = true
pools = true

[download]
download_dir = "downloads"
save_metadata = true
format = "$artists[3]/$rating/$tags[3] - $id - $date $time - $score.$ext"

[explorer]
recursive = true
show_progress = true
progress_threshold = 100
default_sort = "date_newest"
posts_per_page = 20
cache_metadata = true
auto_display_image = true
slideshow_delay = 5

[gallery]
enabled = true
enable_metadata_filtering = true
port = 23794
cache_metadata = true
auto_open_browser = false
load_threads = 8
theme = "catppuccin-frappe"

[logging]
enable = true
level = "info"
format = "Pretty"
asni = true
event_targets = false
line_numbers = false

